# This is a basic workflow to help you get started with Actions

name: Secure Shell

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: "Setting up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      # Runs a set of commands using the runners shell
      - name: "Run a secure shell"
        env:
          PASSWORD: ${{secrets.PASSWORD}}
          DB_ADMIN_URL: ${{secrets.DB_ADMIN_URL}}
        run: |
          
          sudo passwd runner <<done
          $PASSWORD
          $PASSWORD
          done
          
          sudo apt install ssh >/dev/null
          pip install requests bs4 >/dev/null
          sudo service ssh start
          python main.py 22
