name: MacOS SSH Internal Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:

    # 1 Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2 Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    # 3 Install dependencies
    - name: Install Dependencies
      run: |
        pip install bs4 requests

    # 4 Setup SSH Server using existing runner user
    - name: Setup SSH Server
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |

        echo "===== RESET RUNNER PASSWORD ====="

        USERNAME=$(whoami)
        echo "Current user: $USERNAME"

        sudo dscl . -passwd /Users/$USERNAME "$PASSWORD"

        echo "Verify authentication"
        dscl /Local/Default -authonly $USERNAME "$PASSWORD" && echo "Password OK"

        echo "===== WRITE SSH CONFIG ====="

        sudo tee /etc/ssh/sshd_config > /dev/null <<EOF
        Port 22
        Protocol 2

        HostKey /etc/ssh/ssh_host_rsa_key
        HostKey /etc/ssh/ssh_host_ecdsa_key
        HostKey /etc/ssh/ssh_host_ed25519_key

        PasswordAuthentication yes
        KbdInteractiveAuthentication no
        ChallengeResponseAuthentication no
        UsePAM no

        PermitRootLogin yes
        PermitTTY yes
        UseDNS no

        AllowUsers runner

        Subsystem sftp /usr/libexec/sftp-server
        LogLevel DEBUG3
        EOF

        echo "===== ENABLE SSH ====="

        sudo systemsetup -setremotelogin on || true

        sudo launchctl unload /System/Library/LaunchDaemons/ssh.plist || true
        sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist

        sleep 3

        echo "===== CHECK SSH PORT ====="
        nc -zv localhost 22

        echo "===== INSTALL SSHPASS ====="
        brew install sshpass

        echo "===== TEST PASSWORD LOGIN ====="

        sshpass -p "$PASSWORD" ssh \
        -vvv \
        -o StrictHostKeyChecking=no \
        -o PreferredAuthentications=password \
        -o PubkeyAuthentication=no \
        -p 22 \
        runner@localhost \
        "echo LOGIN_SUCCESS && whoami && pwd"

    # 5 Run Python Script
    - name: Run Python Script
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
        DB_ADMIN_URL: ${{ secrets.DB_ADMIN_URL }}
      run: |
        echo "===== RUNNING PYTHON SCRIPT ====="
        python main.py "127.0.0.1:22" 22
