# This is a basic workflow to help you get started with Actions

name: Ubuntu SSH

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - name: Installing Dependencies
        run: |
          sudo apt update
          sudo apt install ssh
          pip install requests bs4
      
      - name: Running a SSH Server
        env:
          PASSWORD: ${{secrets.PASSWORD}}
          DB_ADMIN_URL: ${{secrets.DB_ADMIN_URL}}
        run: |
          sudo passwd runner <<done
          $PASSWORD
          $PASSWORD
          done
          
          sudo service ssh start
          python main.py "ubuntu-ssh-server:22" 22
