name: Windows SSH

on:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    
    - name: Installing Dependencies
      run: |
        choco install openssh
        pip install bs4 requests
        
    - name: Running SSH Sever
      env:
        DB_ADMIN_URL: ${{secrets.DB_ADMIN_URL}}
      run: |
        net user runneradmin ${{secrets.PASSWORD}}
        & 'C:\Program Files\OpenSSH-Win64\install-sshd.ps1'
        & 'C:\Program Files\OpenSSH-Win64\Set-SSHDefaultShell.ps1' 'C:\Windows\System32\cmd.exe'
        net start sshd
        python main.py 22
