name: Windows SSH

on:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    
    - name: Installing Dependencies
      run: |
        choco install openssh
        pip install bs4 requests

    - name: Running SSH Sever
      env:
          DB_ADMIN_URL: ${{secrets.DB_ADMIN_URL}}
      run: |
        net user runner ${{secrets.PASSWORD}}
        Copy-Item "C:\Program Files\OpenSSH-Win64\sshd_config_default" "C:\ProgramData\ssh\sshd_config"
        & 'C:\Program Files\OpenSSH-Win64\install-sshd.ps1'
        echo '' | & 'C:\Program Files\OpenSSH-Win64\ssh-keygen.exe' -N ' '
        & 'C:\Program Files\OpenSSH-Win64\ssh-keygen.exe' -A
        Start-Job -ScriptBlock { & 'C:\Program Files\OpenSSH-Win64\sshd.exe' }
        python main.py 22
        
